# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yb7JhvUTU7RHCJCLR0mBGKZsjpZ30UJ2
"""

import os
import calendar
import numpy as np
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt

# Path dasar folder setelah shortcut ditambahkan ke MyDrive
base_path = '/content/drive/MyDrive/Tugas Manop-Geopot/data_lemi_gea'
output_path = '/content/drive/MyDrive/Data_Valid'

# Buat folder output jika belum ada
os.makedirs(output_path, exist_ok=True)

# Parameter validasi
jumlah_data_per_hari = 86400   # 24 jam * 60 menit * 60 detik
ambang_valid = 0.9             # 90% valid

# Fungsi mengecek apakah satu baris data valid
def is_valid_line(line):
    try:
        parts = line.strip().split()
        if len(parts) < 5:
            return False
        x = float(parts[2])
        y = float(parts[3])
        z = float(parts[4])
        if x == 99999.00 or y == 99999.00 or z == 99999.00:
            return False
        return True
    except:
        return False

# Loop dari bulan 01 sampai 12
for bulan in range(1, 13):
    bulan_folder = f"{bulan:02d}"  # Format '01', '02', ..., '12'
    folder_path = os.path.join(base_path, bulan_folder, 'IAGA', 'vsec')

    if os.path.exists(folder_path):
        print(f"\n📁 Membaca data dari: {folder_path}")
        for filename in sorted(os.listdir(folder_path)):
            file_path = os.path.join(folder_path, filename)
            if os.path.isfile(file_path) and filename.endswith(".sec"):
                with open(file_path, 'r') as file:
                    lines = file.readlines()

                data_lines = [line for line in lines if line[:1].isdigit()]
                valid_lines = [line for line in data_lines if is_valid_line(line)]
                persen_valid = len(valid_lines) / jumlah_data_per_hari

                if persen_valid >= ambang_valid:
                    nama_baru = os.path.splitext(filename)[0] + "_Valid.sec"
                    output_file = os.path.join(output_path, nama_baru)

                    with open(output_file, 'w') as f_out:
                        f_out.writelines(lines)

                    print(f"\n✔ File valid → {filename}")
                    print(f"  - Total baris data: {len(data_lines)}")
                    print(f"  - Baris valid     : {len(valid_lines)}")
                    print(f"  - Persen valid    : {persen_valid:.2%}")
                    print(f"  - Disimpan sebagai: {nama_baru}")
                else:
                    print(f"✘ File tidak valid → {filename} ({persen_valid:.2%})")
    else:
        print(f"⚠ Folder tidak ditemukan: {folder_path}")

# Header
print("📊 Ringkasan Jumlah & Persentase File Valid per Bulan\n")

# Loop tiap bulan
for bulan in range(1, 13):
    nama_bulan = calendar.month_name[bulan]
    bulan_folder = f"{bulan:02d}"
    folder_path = os.path.join(base_path, bulan_folder, 'IAGA', 'vsec')

    jumlah_file = 0
    jumlah_valid = 0
    jumlah_tidak_valid = 0

    if os.path.exists(folder_path):
        sec_files = [f for f in os.listdir(folder_path) if f.endswith('.sec') and os.path.isfile(os.path.join(folder_path, f))]
        jumlah_file = len(sec_files)

        for filename in sec_files:
            file_path = os.path.join(folder_path, filename)
            with open(file_path, 'r') as f:
                lines = f.readlines()
            data_lines = [line for line in lines if line[:1].isdigit()]
            valid_lines = [line for line in data_lines if is_valid_line(line)]
            persen_valid_data = len(valid_lines) / jumlah_data_per_hari

            if persen_valid_data >= ambang_valid:
                jumlah_valid += 1
            else:
                jumlah_tidak_valid += 1

        persen_file_valid = (jumlah_valid / jumlah_file) * 100 if jumlah_file else 0

        print(f"📁 {nama_bulan} ({bulan_folder}):")
        print(f"   - Total file .sec         : {jumlah_file}")
        print(f"   - File valid (≥90%)       : {jumlah_valid}")
        print(f"   - File tidak valid (<90%) : {jumlah_tidak_valid}")
        print(f"   - Persentase valid        : {persen_file_valid:.2f}%\n")
    else:
        print(f"📁 {nama_bulan} ({bulan_folder}): ❌ Folder tidak ditemukan\n")

print("✅ Pemeriksaan file valid/tidak valid selesai.")

folder_path = '/content/drive/MyDrive/Data_Valid'
all_data = []

# Loop semua file di folder
for filename in os.listdir(folder_path):
    # Cek ekstensi .sec dan nama file tidak mengandung '(1)'
    if filename.endswith('.sec') and '(1)' not in filename:
        filepath = os.path.join(folder_path, filename)
        # Baca file, skip 12 baris pertama, tanpa header
        df = pd.read_csv(filepath, sep='\s+', skiprows=13, header=None)

        # Beri nama kolom ulang
        df.columns = ['DATE', 'TIME', 'DOY', 'SRGX', 'SRGY', 'SRGZ', 'SRGF']

        # Simpan ke list
        all_data.append(df)

# Gabungkan semua data dari semua file menjadi satu DataFrame besar (opsional)
data_combined = pd.concat(all_data, ignore_index=True)

# Drop kolom 'DOY'
data_combined = data_combined.drop(columns=['DOY'])

# Drop baris yang mengandung 99999 pada kolom sensor
sensor_columns = ['SRGX', 'SRGY', 'SRGZ', 'SRGF']
data_combined = data_combined[
    ~(data_combined[sensor_columns] == 99999).any(axis=1)
]

# Tampilkan hasilnya
data_combined

print(data_combined.isna().sum())

# 6. Hitung deltaF
data_combined['Fcal'] = np.sqrt(data_combined['SRGX']**2 + data_combined['SRGY']**2 + data_combined['SRGZ']**2)
data_combined['deltaF'] = data_combined['Fcal'] - data_combined['SRGF']
# 7. Ambil semua tanggal unik
unique_dates = sorted(data_combined['DATE'].unique())

data_combined

import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import pandas as pd

# Siapkan list tanggal dan deltaF_range
deltaF_ranges = []
tanggal_list = []

for date in unique_dates:
    daily_data = data_combined[data_combined['DATE'] == date]
    deltaF_range = daily_data['deltaF'].max() - daily_data['deltaF'].min()
    deltaF_ranges.append(deltaF_range)
    tanggal_list.append(pd.to_datetime(date))  # pastikan format datetime

# Warna: hijau jika deltaF < 10, merah jika >= 10
colors = ['green' if val < 10 else 'red' for val in deltaF_ranges]

# Plot scatter
plt.figure(figsize=(15, 6))
plt.scatter(tanggal_list, deltaF_ranges, c=colors, s=30, alpha=0.7, edgecolors='k')

# Garis ambang kualitas
plt.axhline(10, color='blue', linestyle='--', linewidth=1, label='Ambang kualitas (10 nT)')

# Format sumbu X per bulan
plt.gca().xaxis.set_major_locator(mdates.MonthLocator())  # penanda tiap bulan
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%b %Y'))  # format: Jan 2023, Feb 2023, dst

plt.xticks(rotation=45)  # miringkan label agar tidak saling tumpuk

# Label dan tampilan
plt.title('Scatter Plot Rentang deltaF Harian (max - min)')
plt.xlabel('Tanggal')
plt.ylabel('Rentang deltaF (nT)')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()